# Generated by Django 6.0.6 on 2026-07-09 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_is_featured_product_shopier_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Ana Görsel'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/', verbose_name='Galeri Görseli')),
                ('alt_text', models.CharField(blank=True, max_length=180, verbose_name='Alternatif Metin')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sıralama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='products.product', verbose_name='Ürün')),
            ],
            options={
                'verbose_name': 'Ürün Galeri Görseli',
                'verbose_name_plural': 'Ürün Galeri Görselleri',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
    ]
